### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by NabeelAhmed23** [glennreyes/react-countup#655]
I have this component for the past 2 months and it was working fine but today it is giving an error. I cant build my react app. If I comment out this component then my app works fine. When I build my app it gives this error: 
    ReferenceError: window is not defined
    at new CountUp (C:\xampp\htdocs\mellow-nextauth\node_modules\countup.js\dist\countUp.umd.js:146:13) 
    at createCountUpInstance (C:\xampp\htdocs\mellow-nextauth\node_modules\react-countup\build\index.js:154:10)
    at C:\xampp\htdocs\mellow-nextauth\node_modules\react-countup\build\index.js:203:12
    at C:\xampp\htdocs\mellow-nextauth\node_modules\react-countup\build\index.js:135:24
    at C:\xampp\htdocs\mellow-nextauth\node_modules\react-countup\build\index.js:212:22
    at C:\xampp\htdocs\mellow-nextauth\node_modules\react-countup\build\index.js:135:24
    at CountUp (C:\xampp\htdocs\mellow-nextauth\node_modules\react-countup\build\index.js:388:37)       
    at d (C:\xampp\htdocs\mellow-nextauth\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\xampp\htdocs\mellow-nextauth\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\xampp\htdocs\mellow-nextauth\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)

**Comment by dawnerd** [comment]
Started happening to me too once I bumped to latest and react 18

**Comment by johakr** [comment]
created a PR in countUp.js, which will fix this issue: https://github.com/inorganik/countUp.js/pull/286

**Comment by inorganik** [comment]
Thanks @johakr , your PR is merged and it's fixed in CountUp v2.3.1
